filebeat.inputs:
  - type: filestream
    enabled: true
    id: microservice1
    paths:
      - "/logs/microservice1/*.log"  # Microservice 1 logs
    json.keys_under_root: true
    json.add_error_key: true
    json.overwrite_keys: true

output.logstash:
  hosts: ["elk:5044"]
  ssl.enabled: false
