version: '3.7'

services:
  warehouse:
    image: warehouse
    build:
      context: .
      dockerfile: ./apps/warehouse/Dockerfile
    container_name: warehouse
    ports:
      - "3333:3333"
    networks:
      - internal
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3333/health"]
      interval: 1s
      timeout: 1s
      retries: 10

networks:
  internal:
    driver: bridge
