version: '3.7'

services:
  elk:
    image: sebp/elk:latest
    container_name: elk-w
    ports:
      - "5601:5601" # Kibana
      - "9200:9200" # Elasticsearch
      - "5044:5044" # Logstash
    environment:
      - ELASTICSEARCH_STARTUPTIMEOUT=30
      - TZ=Asia/Aqtobe
    volumes:
      - "./services/elk/logstash.conf:/etc/logstash/conf.d/02-beats-input.conf"
      - "elk-data:/var/lib/elasticsearch"
    networks:
      - elk-stack-w
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5601"]
      interval: 10s
      timeout: 5s
      retries: 5

  filebeat:
    build:
      context: ./services/filebeat/
      dockerfile: Dockerfile
    container_name: filebeat-w
    user: root
    volumes:
      - "./logs/microservice1:/logs/microservice1:ro"  # Microservice 1 logs
    depends_on:
      - elk
    networks:
      - elk-stack-w


volumes:
  elk-data:
    driver: local


networks:
  elk-stack-w:
    driver: bridge
